UserParameter=mssql.db.discovery,powershell -NoProfile -ExecutionPolicy Bypass -File "C:\zabbix\scripts\mssql_basename.ps1"
UserParameter=mssql.version,powershell -NoProfile -ExecutionPolicy Bypass -File "C:\zabbix\scripts\mssql_version.ps1"
UserParameter=mssql.instances,powershell -NoProfile -ExecutionPolicy Bypass -File "C:\zabbix\scripts\instances_info.ps1"
UserParameter=mssql.job.discovery,powershell -NoProfile -ExecutionPolicy Bypass -File "C:\zabbix\scripts\mssql_jobs.ps1"
UserParameter=mssql.job.info[*],powershell -NoProfile -ExecutionPolicy Bypass -File "C:\zabbix\scripts\mssql_jobs.ps1" "$1" "$2"
